# Generated by Django 5.1.1 on 2024-10-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_total_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
