# Generated by Django 5.1.1 on 2024-10-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_total_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='portfolio_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
