# Generated by Django 5.1.1 on 2025-04-23 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_portfolio_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='portfolio_value',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_contribution',
        ),
    ]
