# Generated by Django 5.1.1 on 2024-10-13 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='full_name',
            new_name='stock_name',
        ),
    ]
