# Generated by Django 5.1.2 on 2024-10-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_num_of_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='num_of_shares',
            field=models.IntegerField(default=0),
        ),
    ]
