# Generated by Django 5.1.2 on 2024-10-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_cost_alter_transaction_num_of_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cost',
            field=models.CharField(),
        ),
    ]
