# Generated by Django 5.1.1 on 2024-10-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_holdings'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='holdings',
            name='average_price',
            field=models.IntegerField(default=0),
        ),
    ]
