# Generated by Django 5.1.1 on 2025-04-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinformation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliosnapshot',
            name='portfolio_value',
        ),
    ]
